import Head from 'next/head';

export default function Home() {
	return (
		<div className='h-screen grid items-center'>
			<div className='px-16 py-8 lg:w-3/4 lg:mx-auto'>
				<Head>
					<title>Single Price Grid Application</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<header className='mx-auto bg-white px-8'>
					<h2 className='text-cyan font-bold text-lg lg:text-xl py-6'>
						Join our community
					</h2>
					<h3 className='text-brightYellow font-bold pb-6'>
						30-day, hassle-free money back guarantee
					</h3>
					<div className='text-grayishBlue pb-8'>
						<p className='inline-block lg:block'>
							Gain access to our full library of tutorials along with expert
							code reviews.
						</p>
						<p className='inline-block lg:block'>
							Perfect for any developers who are serious about honing their
							skills.
						</p>
					</div>
				</header>
				<main className='mx-auto lg:grid lg:grid-cols-2'>
					<section className='bg-cyan px-8'>
						<h3 className='text-white font-bold lg:text-lg py-6'>
							Monthly Subscription
						</h3>
						<div className='flex items-center pb-6'>
							<p className='text-white font-bold text-3xl mr-2'>$29 </p>
							<span className='text-lightGray text-sm lg:text-base'>
								per month
							</span>
						</div>
						<p className='text-white pb-8'>
							Full access for less than $1 a day
						</p>
						<button className='bg-brightYellow text-white w-full py-4 mb-8 shadow-xl rounded outline-none border-none'>
							Sign Up
						</button>
					</section>
					<section className='bg-green-600 text-white px-8'>
						<h3 className='font-bold text-lg py-6'>Why Us</h3>
						<div className='pb-6'>
							<p>Tutorials by industry experts</p>
							<p>Peer & expert code review</p>
							<p>Coding exercises</p>
							<p>Access to our GitHub repos</p>
							<p>Community forum</p>
							<p>Flashcard decks</p>
							<p>New videos every week</p>
						</div>
					</section>
				</main>
			</div>
		</div>
	);
}
